---
abstract: 'A client for Amazon DynamoDB'
author:
  - 'Rusty Conover <rusty@luckydinosaur.com>'
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Data::Dumper: '0'
  IO::Async::Loop: '0'
  IO::Async::SSL: '0'
  String::Random: '0'
  Test::Differences: '0'
  Test::More: '0'
  Test::Most: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amazon-DynamoDB
requires:
  B: '0'
  Digest::HMAC: '0'
  Digest::SHA: '0'
  Future: '0'
  Future::Utils: '0'
  HTTP::Date: '0'
  HTTP::Request: '0'
  HTTP::StreamParser::Request: '0'
  IO::Async::Timer::Countdown: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  List::UtilsBy: '0'
  MIME::Base64: '0'
  Module::Load: '0'
  Mojo::UserAgent: '0'
  Net::Async::HTTP: '0.30'
  POSIX: '0'
  URI: '0'
  URI::Escape: '0'
  URI::QueryParam: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/rustyconover/Amazon-DynamoDB/issues
  repository: git://github.com/rustyconover/Amazon-DynamoDB.git
version: '0.12'
